### PR TITLE
+ arm64-v8a M1 in supportedArchitectures

### PR DESCRIPTION
**Pull request by AdamLiechty**

### CODE REVIEW

**Comment by AdamLiechty** [comment]
@maliroteh-sf @khawkins should we add this? This addition unblocked me on my new M1 laptop.

**Comment by khawkins** [comment]
Yass! I was hoping to go through a smoke test with aarch64 hardware / tools, but hadn't had a chance to do so yet. Thanks @AdamLiechty !

**Review by maliroteh-sf — APPROVED** [review]
🙌

**Comment by khawkins** [comment]
Hey @AdamLiechty we can merge this as soon as you [do the CLA dance](https://github.com/forcedotcom/lwc-dev-mobile-core/pull/56#issuecomment-1247251500).

**Comment by AdamLiechty** [comment]
Thanks, it doesn't look like I have merge permission, can either of you merge please?

**Pull request merged**
